"""Execute all SPARQL validation rules and write a Markdown report."""

from __future__ import annotations

import sys
from pathlib import Path

from common import (
    REPORT_FILE,
    VALIDATION_QUERY_DIR,
    ProjectError,
    invalid_overlay_graph,
    markdown_table,
    relative,
    result_table,
    run_query,
    valid_graph,
)


RULE_TITLES = {
    "V01": "Missing contract item",
    "V02": "Duplicate contract item code",
    "V03": "Item name mismatch",
    "V04": "Specification mismatch",
    "V05": "Unit mismatch",
    "V06": "Contract unit price mismatch",
    "V07": "Previous approved value mismatch",
    "V08": "Cumulative quantity calculation error",
    "V09": "Contract quantity exceeded",
    "V10": "Remaining quantity calculation error",
    "V11": "Current progress amount calculation error",
    "V12": "Cumulative amount calculation error",
    "V13": "Work summary calculation error",
    "V14": "Missing required value",
    "V15": "Negative or abnormal value",
}


def execute_rules(graph, query_paths: list[Path]) -> dict[str, tuple[list[str], list[list[str]]]]:
    """Run validation rules and materialize all result rows once."""

    output: dict[str, tuple[list[str], list[list[str]]]] = {}
    for path in query_paths:
        result = run_query(graph, path)
        output[path.stem[:3]] = result_table(result)
    return output


def build_report(
    query_paths: list[Path],
    valid_results: dict[str, tuple[list[str], list[list[str]]]],
    invalid_results: dict[str, tuple[list[str], list[list[str]]]],
) -> str:
    """Build the validation report in a deterministic order."""

    lines = [
        "# SPARQL Validation Report",
        "",
        "This report was generated by `scripts/generate_validation_report.py`.",
        "The datasets are **synthetic example data**, not records from an actual public project.",
        "",
        "## Test Policy",
        "",
        "- Valid data passes when every validation query returns zero rows.",
        "- The invalid overlay passes its test when every validation query detects at least one row.",
        "- Quantity tolerance: `0.0001`.",
        "- Amount tolerance: `0.5 KRW`.",
        "",
        "## Summary",
        "",
        "| Rule | Description | Valid data | Invalid overlay |",
        "|---|---|---:|---:|",
    ]

    for path in query_paths:
        rule_id = path.stem[:3]
        valid_count = len(valid_results[rule_id][1])
        invalid_count = len(invalid_results[rule_id][1])
        valid_status = f"{valid_count} (PASS)" if valid_count == 0 else f"{valid_count} (FAIL)"
        invalid_status = f"{invalid_count} (DETECTED)" if invalid_count > 0 else "0 (MISSED)"
        lines.append(f"| {rule_id} | {RULE_TITLES[rule_id]} | {valid_status} | {invalid_status} |")

    lines.extend(["", "## Invalid Overlay Details", ""])
    for path in query_paths:
        rule_id = path.stem[:3]
        headers, rows = invalid_results[rule_id]
        lines.extend(
            [
                f"### {rule_id}. {RULE_TITLES[rule_id]}",
                "",
                f"Query: `{relative(path)}`",
                "",
                markdown_table(headers, rows[:5]),
                "",
            ]
        )
        if len(rows) > 5:
            lines.extend([f"_Showing 5 of {len(rows)} detected rows._", ""])

    lines.extend(
        [
            "## Result",
            "",
            "The valid dataset produced no validation errors, and every intentional invalid case was detected.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    try:
        query_paths = sorted(VALIDATION_QUERY_DIR.glob("V*.rq"))
        if len(query_paths) != 15:
            raise ProjectError(f"Expected 15 validation queries, found {len(query_paths)}.")

        valid_results = execute_rules(valid_graph(), query_paths)
        invalid_results = execute_rules(invalid_overlay_graph(), query_paths)
        valid_failures = [rule for rule, (_, rows) in valid_results.items() if rows]
        missed_invalid = [rule for rule, (_, rows) in invalid_results.items() if not rows]

        REPORT_FILE.parent.mkdir(parents=True, exist_ok=True)
        REPORT_FILE.write_text(
            build_report(query_paths, valid_results, invalid_results),
            encoding="utf-8",
        )
        print(f"Wrote {relative(REPORT_FILE)}")
        print(f"Valid-data failures: {len(valid_failures)}")
        print(f"Invalid rules detected: {15 - len(missed_invalid)}/15")

        if valid_failures or missed_invalid:
            if valid_failures:
                print(f"[ERROR] Valid data failed: {', '.join(valid_failures)}", file=sys.stderr)
            if missed_invalid:
                print(f"[ERROR] Invalid cases missed: {', '.join(missed_invalid)}", file=sys.stderr)
            return 1
        return 0
    except Exception as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
